// Block: ITF_A01

TYPE ITF_A01
VERSION : 0.1
   STRUCT
      AreaInterface : AreaInterface;
      CoilHandling_MachineInterface : MachineInterface;
      Infeed_REQ_ON : Bool;
      PB : Struct;
      Safety_SuperUser : Struct;
      Safety_EntryEnable : Struct;
      Safety_CtrlSafe : Struct;
      Doors_Closed : Bool;
      Production_Running : Bool;
      Production_Halted : Struct;
      MaterialCounter : MatCountData;
      MaterialPresence : Bool;
      MaterialPresence_StraightenerEntry : Bool;
      MaterialPresence_StraightenerExit : Bool;
      MaterialPresence_JBPinchExit : Bool;
      Material_STS : Int;
      Decoiler_InLine : Int;
      Coil_Diameter : Real;
      WeldDone : Bool;
      Deroga_Spessore_Errato : Bool;
      Spessore_Lamiera_Errato : Bool;
      Spessore_Lamiera_Errore_Valore : Real;
      Spessore_Lamiera_Sensore_Valore : Real;
      Provino_Eseguito : Bool;
      Loop1_COut : SmartLoopControl_COut;
      Loop1_Lamp : Bool;
      Loop1_MachineInterface : MachineInterface;
      NxtEndOfMaterial : Bool;
      EmptyingConfirmed : Bool;
      StraightnerPowerOn : Bool;
      FreeBool : Array[1..16] of Bool;
      FreeLReal : Array[1..16] of LReal;
      FreeDINT : Array[1..16] of DInt;
   END_STRUCT;
END_TYPE
