// Block: AreaXX_FinalCutLub_CALL
// Title: Dies lubrication call (AreaXX)

FUNCTION "AreaXX_FinalCutLub_CALL" : Void
{ S7_Optimized_Access := 'TRUE' }
VERSION : 0.1

BEGIN
   REGION "Call"
      // TODO: replace AreaXX with actual area instance
      #AreaXX_FinalCutLub(
         en := TRUE,
         AreaInterface := AreaXX.AreaInterface
      );

      #AreaXX_FinalCutLub.Q;
   END_REGION

END_FUNCTION
