// Block: Trapezoidal_PeekVelocity
// Title: mm/min

FUNCTION "Trapezoidal_PeekVelocity" : Void
{ S7_Optimized_Access := 'TRUE' }
VERSION : 0.1
// mm/min
   VAR_INPUT
      FeedSpace : LReal;
      AccDec : LReal;
   END_VAR

   VAR_TEMP
      Ramp_Space : LReal;
      Ramp_Time : LReal;
   END_VAR


BEGIN
   REGION "mm/min"
      Trapezoidal_PeekVelocity := (FeedSpace * AccDec) * 60.0;




   END_REGION


END_FUNCTION
